/* Generated by nMigen Yosys 0.9+3527 (PyPI ver 0.9.post3527.dev27, git sha1 a0177569) */

module top(clk, rst, led);
  reg \initial  = 0;
  wire [24:0] \$1 ;
  wire [24:0] \$2 ;
  input clk;
  reg [23:0] counter = 24'h000000;
  reg [23:0] \counter$next ;
  output led;
  input rst;
  assign \$2  = counter + 1'h1;
  always @(posedge clk)
    counter <= \counter$next ;
  always @* begin
    if (\initial ) begin end
    \counter$next  = \$1 [23:0];
    casez (rst)
      1'h1:
          \counter$next  = 24'h000000;
    endcase
  end
  assign \$1  = \$2 ;
  assign led = counter[23];
endmodule
