# Set up bank 66 to be impedence matched
set_property DCI_CASCADE {66} [get_iobanks 65]

# Trigger pins
set_property SLEW SLOW [get_ports {TRIG0[0]}]
set_property SLEW SLOW [get_ports {TRIG1[0]}]
set_property PACKAGE_PIN G5 [get_ports {TRIG0[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG0[0]}]
set_property PACKAGE_PIN H4 [get_ports {TRIG1[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG1[0]}]
set_property PACKAGE_PIN C9 [get_ports {TRIG2[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG2[0]}]
set_property PACKAGE_PIN D11 [get_ports {TRIG3[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TRIG3[0]}]
set_property PACKAGE_PIN B4 [get_ports {TRIG4[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG4[0]}]
set_property PACKAGE_PIN T6 [get_ports {TRIG5[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG5[0]}]
set_property DRIVE 8 [get_ports {TRIG3[0]}]

# Enable pins
set_property PACKAGE_PIN L2 [get_ports {ENABLE[5]}]
set_property PACKAGE_PIN A4 [get_ports {ENABLE[4]}]
set_property PACKAGE_PIN E10 [get_ports {ENABLE[3]}]
set_property PACKAGE_PIN B9 [get_ports {ENABLE[2]}]
set_property PACKAGE_PIN H3 [get_ports {ENABLE[1]}]
set_property PACKAGE_PIN A1 [get_ports {ENABLE[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ENABLE[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[0]}]
set_property DRIVE 8 [get_ports {ENABLE[3]}]

# i2c definitions
set_property PACKAGE_PIN A2 [get_ports iic_rtl_0_scl_io]
set_property PACKAGE_PIN F5 [get_ports iic_rtl_0_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_0_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_0_sda_io]
set_property PACKAGE_PIN H9 [get_ports iic_rtl_1_scl_io]
set_property PACKAGE_PIN H8 [get_ports iic_rtl_1_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_1_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_1_sda_io]
set_property PACKAGE_PIN E9 [get_ports iic_rtl_2_scl_io]
set_property PACKAGE_PIN D9 [get_ports iic_rtl_2_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_2_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_2_sda_io]
set_property PACKAGE_PIN D10 [get_ports iic_rtl_3_scl_io]
set_property PACKAGE_PIN E12 [get_ports iic_rtl_3_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports iic_rtl_3_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports iic_rtl_3_sda_io]
set_property PACKAGE_PIN A3 [get_ports iic_rtl_4_scl_io]
set_property PACKAGE_PIN B3 [get_ports iic_rtl_4_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_4_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_4_sda_io]
set_property PACKAGE_PIN R6 [get_ports iic_rtl_5_scl_io]
set_property PACKAGE_PIN L3 [get_ports iic_rtl_5_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_5_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_5_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_0_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_0_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_1_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_1_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_2_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_2_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_3_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_3_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_4_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_4_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_5_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_5_sda_io]

# User definitions
set_property PACKAGE_PIN AC14 [get_ports {USER_LEDS[0]}]
set_property PACKAGE_PIN AC13 [get_ports {USER_LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USER_LEDS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USER_LEDS[1]}]
set_property PACKAGE_PIN W12 [get_ports USER_DIP]
set_property IOSTANDARD LVCMOS33 [get_ports USER_DIP]
set_property PACKAGE_PIN AH12 [get_ports {GPIO[0]}]
set_property PACKAGE_PIN AH11 [get_ports {GPIO[1]}]
set_property PACKAGE_PIN AF11 [get_ports {GPIO[2]}]
set_property PACKAGE_PIN AG11 [get_ports {GPIO[3]}]
set_property PACKAGE_PIN AB10 [get_ports {GPIO[4]}]
set_property PACKAGE_PIN AB9 [get_ports {GPIO[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[0]}]

# i2c headers
set_property PACKAGE_PIN AH14 [get_ports qwiic_rtl_0_scl_io]
set_property PACKAGE_PIN AG14 [get_ports qwiic_rtl_0_sda_io]
set_property PACKAGE_PIN AB13 [get_ports qwiic_rtl_1_scl_io]
set_property PACKAGE_PIN AA13 [get_ports qwiic_rtl_1_sda_io]
set_property PACKAGE_PIN AD14 [get_ports qwiic_rtl_2_scl_io]
set_property PACKAGE_PIN AD15 [get_ports qwiic_rtl_2_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_1_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_1_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_2_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_2_sda_io]

# Debug
set_property PACKAGE_PIN B15 [get_ports {TRIG_PROBE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TRIG_PROBE[0]}]
set_property PACKAGE_PIN AE12 [get_ports {FRAME_START_0[0]}]
set_property PACKAGE_PIN AF12 [get_ports {FRAME_END_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FRAME_END_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FRAME_START_0[0]}]

set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxdatahs[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxdatahs[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxdatahs[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxdatahs[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxdatahs[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxdatahs[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxdatahs[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxdatahs[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]
set_property MARK_DEBUG false [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxsynchs]
set_property MARK_DEBUG false [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl0_rxvalidhs]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl1_rxdatahs[0]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl1_rxdatahs[1]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl1_rxdatahs[2]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl1_rxdatahs[3]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl1_rxdatahs[4]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl1_rxdatahs[5]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl1_rxdatahs[6]}]
set_property MARK_DEBUG false [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/dl1_rxdatahs[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXSYNCHS]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXVALIDHS]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/line_end_inverter2_Res]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/line_counter/U0/ip2bus_data[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/line_counter/U0/ip2bus_data[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/line_counter/U0/ip2bus_data[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/line_counter/U0/ip2bus_data[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/line_counter/U0/ip2bus_data[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXSYNCHS]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXVALIDHS]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/rx_m_axis_TLAST]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/rx_m_axis_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam5/line_end_inverter5_Res]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/line_counter/U0/ip2bus_data[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/line_counter/U0/ip2bus_data[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/line_counter/U0/ip2bus_data[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/line_counter/U0/ip2bus_data[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam5/line_counter/U0/ip2bus_data[4]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy/inst/inst/rxbyteclkhs]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]} {design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXSYNCHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXVALIDHS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/rx_m_axis_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/mipi/cam5/mipi_csi2_rx_subsystem/inst/rx_m_axis_TLAST]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/inst/inst/rxbyteclkhs]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 8 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXSYNCHS]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXVALIDHS]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TLAST]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TVALID]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_rxbyteclkhs]
