# Set up bank 66 to be impedence matched
set_property DCI_CASCADE {66} [get_iobanks 65]

# Trigger pins
set_property SLEW SLOW [get_ports {TRIG0[0]}]
set_property SLEW SLOW [get_ports {TRIG1[0]}]
set_property PACKAGE_PIN G5 [get_ports {TRIG0[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG0[0]}]
set_property PACKAGE_PIN H4 [get_ports {TRIG1[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG1[0]}]
set_property PACKAGE_PIN C9 [get_ports {TRIG2[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG2[0]}]
set_property PACKAGE_PIN D11 [get_ports {TRIG3[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TRIG3[0]}]
set_property PACKAGE_PIN B4 [get_ports {TRIG4[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG4[0]}]
set_property PACKAGE_PIN T6 [get_ports {TRIG5[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {TRIG5[0]}]
set_property DRIVE 8 [get_ports {TRIG3[0]}]

# Enable pins
set_property PACKAGE_PIN L2 [get_ports {ENABLE[5]}]
set_property PACKAGE_PIN A4 [get_ports {ENABLE[4]}]
set_property PACKAGE_PIN E10 [get_ports {ENABLE[3]}]
set_property PACKAGE_PIN B9 [get_ports {ENABLE[2]}]
set_property PACKAGE_PIN H3 [get_ports {ENABLE[1]}]
set_property PACKAGE_PIN A1 [get_ports {ENABLE[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[5]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ENABLE[3]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[2]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[1]}]
set_property IOSTANDARD LVCMOS12 [get_ports {ENABLE[0]}]
set_property DRIVE 8 [get_ports {ENABLE[3]}]

# i2c definitions
set_property PACKAGE_PIN A2 [get_ports iic_rtl_0_scl_io]
set_property PACKAGE_PIN F5 [get_ports iic_rtl_0_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_0_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_0_sda_io]
set_property PACKAGE_PIN H9 [get_ports iic_rtl_1_scl_io]
set_property PACKAGE_PIN H8 [get_ports iic_rtl_1_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_1_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_1_sda_io]
set_property PACKAGE_PIN E9 [get_ports iic_rtl_2_scl_io]
set_property PACKAGE_PIN D9 [get_ports iic_rtl_2_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_2_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_2_sda_io]
set_property PACKAGE_PIN D10 [get_ports iic_rtl_3_scl_io]
set_property PACKAGE_PIN E12 [get_ports iic_rtl_3_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports iic_rtl_3_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports iic_rtl_3_sda_io]
set_property PACKAGE_PIN A3 [get_ports iic_rtl_4_scl_io]
set_property PACKAGE_PIN B3 [get_ports iic_rtl_4_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_4_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_4_sda_io]
set_property PACKAGE_PIN R6 [get_ports iic_rtl_5_scl_io]
set_property PACKAGE_PIN L3 [get_ports iic_rtl_5_sda_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_5_scl_io]
set_property IOSTANDARD LVCMOS12 [get_ports iic_rtl_5_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_0_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_0_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_1_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_1_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_2_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_2_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_3_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_3_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_4_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_4_sda_io]
set_property DRIVE 8 [get_ports iic_rtl_5_scl_io]
set_property DRIVE 8 [get_ports iic_rtl_5_sda_io]

# User definitions
set_property PACKAGE_PIN AC14 [get_ports {USER_LEDS[0]}]
set_property PACKAGE_PIN AC13 [get_ports {USER_LEDS[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USER_LEDS[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USER_LEDS[1]}]
set_property PACKAGE_PIN W12 [get_ports USER_DIP]
set_property IOSTANDARD LVCMOS33 [get_ports USER_DIP]
set_property PACKAGE_PIN AH12 [get_ports {GPIO[0]}]
set_property PACKAGE_PIN AH11 [get_ports {GPIO[1]}]
set_property PACKAGE_PIN AF11 [get_ports {GPIO[2]}]
set_property PACKAGE_PIN AG11 [get_ports {GPIO[3]}]
set_property PACKAGE_PIN AB10 [get_ports {GPIO[4]}]
set_property PACKAGE_PIN AB9 [get_ports {GPIO[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GPIO[0]}]

# i2c headers
set_property PACKAGE_PIN AH14 [get_ports qwiic_rtl_0_scl_io]
set_property PACKAGE_PIN AG14 [get_ports qwiic_rtl_0_sda_io]
set_property PACKAGE_PIN AB13 [get_ports qwiic_rtl_1_scl_io]
set_property PACKAGE_PIN AA13 [get_ports qwiic_rtl_1_sda_io]
set_property PACKAGE_PIN AD14 [get_ports qwiic_rtl_2_scl_io]
set_property PACKAGE_PIN AD15 [get_ports qwiic_rtl_2_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_1_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_1_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_2_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports qwiic_rtl_2_sda_io]

# Debug
set_property PACKAGE_PIN B15 [get_ports {TRIG_PROBE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {TRIG_PROBE[0]}]
set_property PACKAGE_PIN AE12 [get_ports {FRAME_START_0[0]}]
set_property PACKAGE_PIN AF12 [get_ports {FRAME_END_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FRAME_END_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FRAME_START_0[0]}]

set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[57]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[58]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[60]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[62]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[63]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[52]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[44]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[48]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[59]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[61]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[56]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[53]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[54]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[55]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[40]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[49]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[50]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[51]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDEST[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDEST[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDEST[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDEST[3]}]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TVALID]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_aclk]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXSYNCHS]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tlast]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[44]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[40]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[10]}]
set_property MARK_DEBUG true [get_nets design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tvalid]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[9]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/zynq_ultra_ps_e_0/inst/pl_clk1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 48 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[0]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[1]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[2]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[3]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[4]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[5]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[6]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[7]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[8]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[9]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[10]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[11]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[12]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[13]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[14]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[15]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[16]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[17]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[18]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[19]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[20]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[21]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[22]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[23]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[24]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[25]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[26]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[27]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[28]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[29]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[30]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[31]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[32]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[33]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[34]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[35]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[36]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[37]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[38]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[39]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[40]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[41]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[42]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[43]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[44]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[45]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[46]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdata[47]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[0]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[1]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[2]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[3]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[4]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[5]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[6]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[7]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[8]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tdest[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 64 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[0]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[1]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[2]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[3]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[4]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[5]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[6]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[7]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[8]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[9]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[10]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[11]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[12]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[13]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[14]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[15]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[16]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[17]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[18]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[19]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[20]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[21]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[22]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[23]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[24]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[25]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[26]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[27]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[28]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[29]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[30]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[31]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[32]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[33]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[34]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[35]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[36]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[37]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[38]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[39]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[40]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[41]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[42]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[43]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[44]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[45]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[46]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[47]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[48]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[49]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[50]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[51]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[52]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[53]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[54]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[55]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[56]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[57]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[58]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[59]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[60]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[61]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[62]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDEST[0]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDEST[1]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDEST[2]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TDEST[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/rx_m_axis_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/video_out_tvalid]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy/inst/inst/rxbyteclkhs]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[0]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[1]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[2]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[3]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[4]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[5]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[6]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXDATAHS[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 8 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[0]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[1]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[2]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[3]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[4]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[5]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[6]} {design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL1_RXDATAHS[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list design_1_i/mipi/cam2/mipi_csi2_rx_subsystem/inst/phy_rx_mipi_ppi_if_DL0_RXSYNCHS]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
