#!/bin/bash

if [[ -z "${OVC_MINI_DIR}" ]]; then
  echo "Source setup.sh before running this script."
  exit
fi

DISTRO="${DISTRO:-karo-minimal}"
MACHINE="${MACHINE:-qsxp-ml81}"
BUILD_PRJ="${BUILD_PRJ:-build-karo-nxp}"
IMAGE="${IMAGE:-karo-image-minimal}"

BSP_DIR=$OVC_MINI_DIR/bsp

# Custom test image:
# DISTRO=osrf-ovc
# BUILD_PRJ=build-osrf-ovc
# IMAGE=osrf-image-ovc

setup_release () {
  source karo-setup-release.sh -b $BUILD_PRJ
}

rebuild () {
  source setup-environment $BUILD_PRJ
}

cd $BSP_DIR
if [[ -z "${BUILD_PRJ}" ]]; then
  setup_release
else
  rebuild
fi

echo "Bitbake seems to not like being run from within a shell script."
echo "Please run the following command to build:"
echo "    bitbake $IMAGE"
