#!/bin/bash

if [[ -z "${OVC_MINI_DIR}" ]]; then
  echo "Source setup.sh before running this script."
  exit
fi

DISTRO="${DISTRO:-ovc-mini}"
MACHINE="${MACHINE:-qsxp-ml81}"
BUILD_PRJ="${BUILD_PRJ:-build-ovc}"
IMAGE="${IMAGE:-ovc-image}"

BSP_DIR=$OVC_MINI_DIR/bsp

setup_release () {
  source karo-setup-release.sh -b $BUILD_PRJ && bitbake $IMAGE
}

rebuild () {
  source setup-environment $BUILD_PRJ && bitbake $IMAGE
}

cd $BSP_DIR
if [[ -z "${BUILD_PRJ}" ]]; then
  setup_release
else
  rebuild
fi
