FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
SRC_URI += " file://si5338.patch"
SRC_URI += " file://devtool-fragment.cfg"
SRC_URI_append += "file://0001-Change-bMaxBurst-and-qlen-to-the-highest-number.patch"
IMAGE_INSTALL_append = "kernel-devsrc"
