name: clang-format Check
# See https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v3.3.0
      with:
        clang-format-version: '11'
        check-path: 'ovc5/software'
